### ISSUE TITLE
Compilation failure with Swift 4

### ISSUE THREAD

**Issue by akosma** [rhx/gir2swift#1]
I was trying to build some of your projects (SwiftGtk, SwiftHelloGtkBuilder) and they all fail with the latest Swift:

Swift version 4.0 (swift-4.0-RELEASE)
Target: x86_64-unknown-linux-gnu

Running Ubuntu 16.04 64 bits:

Linux 4.10.0-35-generic #39~16.04.1-Ubuntu SMP Wed Sep 13 09:02:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

The error can be reproduced just by cloning any of the repos, cd'ing into them, and then running the enclosed `build.sh`. I have installed all the library requirements. The error message is in the file attached: [error.txt](https://github.com/rhx/gir2swift/files/1324438/error.txt)

The compilations of all the aforementioned projects stop when the gir2swift project is building, this is why I post this bug here.

**Comment by rhx** [comment]
I have fixed the "expression was too complex" error now, so it compiles under Swift 4 (in Swift 3 compatibility mode).  However, even in Swift 3 compatibility mode, the output generated by gir2swift is wrong.  So it looks like this needs a bit or a re-write to work with the new Swift 4 String type implementation.

**Comment by rhx** [comment]
This should be working now, can you give it a try?  I have updated gir2swift and most downstream packages (including SwiftGtk and SwiftHelloGtkBuilder), and they are compiling fine for me now with Swift 4 under Ubuntu 16.04 and macOS.
