### ISSUE TITLE
Use element-type for lists/hash tables

### ISSUE THREAD

**Issue by QuLogic** [rhx/gir2swift#24]
From what I've been able to figure out, it appears that `GList`/`GSList` are exposed in way that is similar to C, but it doesn't transform the type into a Swift equivalent. If I have a [return type with `element-type` annotation](https://gi.readthedocs.io/en/latest/annotations/giannotations.html#type-signature):
```
/**
 * example_get_list:
 *
 * Returns a list of strings.
 *
 * Returns: (element-type utf8) (transfer container): A list of strings.
 */                                                                             
GList *
example_get_list(void) {
    GList *list = NULL;

    list = g_list_append(list, "foo");
    list = g_list_append(list, "bar");
    list = g_list_append(list, "baz");

    return list;
}                           
```
then in C, I know I can treat that as:
```
GList *list = example_get_list();
while(list != NULL) {
    const gchar *value = list->data;
    printf("List value: %s\n", value);
    list = list->next;
}
g_list_free(list);
```
Depending on [the mode in the `transfer` annotation](https://gi.readthedocs.io/en/latest/annotations/giannotations.html#memory-and-lifecycle-management), I would also know whether to free the list only, its contents as well, or none of it.

In Python for example, said list would be converted to a Python `list` object with `str`s, hiding the whole linked-list data structure. All of the freeing stuff is also hidden.

With the Swift binding, I _think_ this ends up being handled in a manual (for Swift) way:
```
import Example
let list = Example.getList()
while list != nil {
    let value = String(validatingUTF8: l_id!.data!.assumingMemoryBound(to: CChar.self))
    print("List value: \(value)")
    l_id = l_id?.next
}
l_ids?.free()
```

I don't know if doing full conversion like Python is the best choice in Swift, or whether it can be hidden behind some Protocol, but it would be nice to wrap the element types at least.

An example of one of these in GTK is `gtk_application_get_windows`. In the best case, the binding for this should be a list of Window objects (or at least something that appears that way in a Swift-like way.)

Note, I've only spent about two days investigating how easy it would be to create Swift bindings for a gir library, and don't actually know any Swift outside of that, so I apologize if my explanations of that side of things do not make any sense.

**Comment by rhx** [comment]
This is now implemented on the development branch.

**Comment by rhx** [comment]
This is now available on the main branch (as of gir2swift version 16).
