### ISSUE TITLE
Includes error

### ISSUE THREAD

**Issue by imvm** [rhx/gir2swift#3]
Hello.

I am trying to use your library to parse a .gir to Swift, but am having no success.  When running `swift run` I get the following errors:

`<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "libxml/HTMLparser.h"
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/libxml2/libxml/HTMLparser.h:15:10: error: 'libxml/xmlversion.h' file not found
#include <libxml/xmlversion.h>
         ^
/Users/roadmaps/arrow-apache-arrow-0.13.0/c_glib/gir2swift/.build/checkouts/SwiftLibXML/Sources/SwiftLibXML/XMLAttribute.swift:13:12: error: could not build Objective-C module 'libxml2'
    import libxml2
           ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "libxml/HTMLparser.h"
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/libxml2/libxml/HTMLparser.h:15:10: error: 'libxml/xmlversion.h' file not found
#include <libxml/xmlversion.h>
         ^
/Users/roadmaps/arrow-apache-arrow-0.13.0/c_glib/gir2swift/.build/checkouts/SwiftLibXML/Sources/SwiftLibXML/XMLAttribute.swift:13:12: error: could not build Objective-C module 'libxml2'
    import libxml2
           ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "libxml/HTMLparser.h"
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/libxml2/libxml/HTMLparser.h:15:10: error: 'libxml/xmlversion.h' file not found
#include <libxml/xmlversion.h>
         ^
/Users/roadmaps/arrow-apache-arrow-0.13.0/c_glib/gir2swift/.build/checkouts/SwiftLibXML/Sources/SwiftLibXML/XMLAttribute.swift:13:12: error: could not build Objective-C module 'libxml2'
    import libxml2
           ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "libxml/HTMLparser.h"
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/libxml2/libxml/HTMLparser.h:15:10: error: 'libxml/xmlversion.h' file not found
#include <libxml/xmlversion.h>
         ^
/Users/roadmaps/arrow-apache-arrow-0.13.0/c_glib/gir2swift/.build/checkouts/SwiftLibXML/Sources/SwiftLibXML/XMLAttribute.swift:13:12: error: could not build Objective-C module 'libxml2'
    import libxml2
           ^`

**Comment by rhx** [comment]
You need to install `libxml2` using HomeBrew (see the updated `README.md` for details).  However, you don't usually build this manually.  See, for example, my SwiftGtk project for some scripts that use the gir2swift tool.

**Comment by imvm** [comment]
I've installed `libxml2` using Homebrew, unfortunately I get the same error. I believe the problem is related to the fact that you can't link libxml2 in Homebrew because it is already provided by macOS, if you try to do so it just recommends settings some environment variables instead. Therefore `swift build` is probably getting the system's version of `libxml2` which won't have the necessary headers. Setting the `PATH`, `LDFLAGS`, `CPPFLAGS` and `PKG_CONFIG_PATH` variables don't seem to help so I'm kind of lost. 

I am also taking a look at SwiftGtk to see if I can find something that will help solve my problem.

**Comment by rhx** [comment]
Can you check if this is still happening to you with current versions of Xcode and Homebrew?
